### ISSUE TITLE
Update readme w

### ISSUE THREAD

**Issue by eudangeld** [eudangeld/simple_dart_tools#4]
Update readme add use for phone

**Comment by abhishekpatel946** [comment]
### **Hey @eudangeld ,**
I'm ready to update README.md  `_but can you tell me what exactly you want to change_`

**Comment by eudangeld** [comment]
> ### **Hey @eudangeld ,**
> I'm ready to update README.md `_but can you tell me what exactly you want to change_`

Hey @abhishekpatel946  thanks for comming.
I'm finising an implementation here, when done i will call u.
I just want to some examples using this library, right now i'm writing a new validation....

**Comment by abhishekpatel946** [comment]
sure ... thanks for replying to me
if you want to need a README.md from scratch or some changes to your pre-build ReadMe.md that's not the problem.

**Comment by abhishekpatel946** [comment]
Ohh sure @eudangeld sir, You can reach me and assign it to me. I love to contribute with yours

**Comment by eudangeld** [comment]
You can write a good readme exemple now.
This class is simple you can review the code too.
Thanks

**Comment by eudangeld** [comment]
> Ohh sure @eudangeld sir, You can reach me and assign it to me. I love to contribute with yours
@abhishekpatel946 
You can write a good readme exemple now.

This class is simple you can review the code too.
Thanks

**Comment by abhishekpatel946** [comment]
ohks thanks! 
I can a README.md after you change a bit then it works.

> add your features

> description of your project

that's it
